From here:
http://lab.safermobile.org/wiki/OurSoftwareProcess


** Core Principles

We use free software whenever possible to reduce impediments for others to build upon what we have done
All code is licensed under open-source licenses, and mostly the GPL v3.

** Development Tools

Eclipse IDE: www.eclipse.org/
Android SDK with Eclipse Integration: developer.android.com/sdk/index.html
Mobile Tools for Java: www.eclipse.org/mtj/
Blackberry Java Dev: us.blackberry.com/developers/javaappdev/
Symbian/Nokia Java Dev: www.forum.nokia.com/Library/Tools_and_downloads/Other/Symbian_SDKs/[[]]

** Code Management

Git and Github for code management: github.com/SaferMobile/
Jenkins for Continous Integration: jenkins-ci.org/

** Community Interaction

SaferMobile on IRC: freenode.net/irc_servers.shtml
Developer Mailing list: https://lab.safermobile.org/mailman/listinfo/dev
Public Milestones and Issue tracking: github.com/SaferMobile/InTheClear/issues